# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='io.proto',
  package='io',
  syntax='proto2',
  serialized_pb=_b('\n\x08io.proto\x12\x02io\".\n\x0bSetVelocity\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"\x0b\n\tHeartbeat\"!\n\x07SetMode\x12\x16\n\x04mode\x18\x01 \x02(\x0e\x32\x08.io.Mode*\"\n\x04Mode\x12\x0c\n\x08VELOCITY\x10\x00\x12\x0c\n\x08POSITION\x10\x01')
)

_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='io.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VELOCITY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=112,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_MODE)

Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
VELOCITY = 0
POSITION = 1



_SETVELOCITY = _descriptor.Descriptor(
  name='SetVelocity',
  full_name='io.SetVelocity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='io.SetVelocity.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='io.SetVelocity.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='io.SetVelocity.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=62,
)


_HEARTBEAT = _descriptor.Descriptor(
  name='Heartbeat',
  full_name='io.Heartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=75,
)


_SETMODE = _descriptor.Descriptor(
  name='SetMode',
  full_name='io.SetMode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='io.SetMode.mode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=110,
)

_SETMODE.fields_by_name['mode'].enum_type = _MODE
DESCRIPTOR.message_types_by_name['SetVelocity'] = _SETVELOCITY
DESCRIPTOR.message_types_by_name['Heartbeat'] = _HEARTBEAT
DESCRIPTOR.message_types_by_name['SetMode'] = _SETMODE
DESCRIPTOR.enum_types_by_name['Mode'] = _MODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetVelocity = _reflection.GeneratedProtocolMessageType('SetVelocity', (_message.Message,), dict(
  DESCRIPTOR = _SETVELOCITY,
  __module__ = 'io_pb2'
  # @@protoc_insertion_point(class_scope:io.SetVelocity)
  ))
_sym_db.RegisterMessage(SetVelocity)

Heartbeat = _reflection.GeneratedProtocolMessageType('Heartbeat', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEAT,
  __module__ = 'io_pb2'
  # @@protoc_insertion_point(class_scope:io.Heartbeat)
  ))
_sym_db.RegisterMessage(Heartbeat)

SetMode = _reflection.GeneratedProtocolMessageType('SetMode', (_message.Message,), dict(
  DESCRIPTOR = _SETMODE,
  __module__ = 'io_pb2'
  # @@protoc_insertion_point(class_scope:io.SetMode)
  ))
_sym_db.RegisterMessage(SetMode)


# @@protoc_insertion_point(module_scope)
